// WARNING: This file has automatically been generated on Fri, 24 May 2024 14:49:00 CEST.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

#include "ezkl-ffi.h"
#include <stdlib.h>
#pragma once

#define __CGOGEN 1

