// WARNING: This file has automatically been generated on Thu, 23 May 2024 20:51:35 CEST.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

#include "ezkl-ffi.h"
#include <stdlib.h>
#pragma once

#define __CGOGEN 1

